# Generated by Django 5.0.7 on 2024-08-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_username_signin_db_confirm_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin_db',
            old_name='Name',
            new_name='Username',
        ),
    ]
