# Generated by Django 5.0.7 on 2024-08-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_name_signin_db_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin_db',
            old_name='Username',
            new_name='Uname',
        ),
    ]
