# Generated by Django 5.0.7 on 2024-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_username_signin_db_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin_db',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
