# Generated by Django 5.0.7 on 2024-08-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_signin_db_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signin_db',
        ),
    ]
