# Generated by Django 5.0.7 on 2024-08-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_proceed_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceed_db',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
